name: Build And Push DongTai Base Image To Aliyun Repo

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_DOCKERHUB_USER }}
          password: ${{ secrets.ALIYUN_DOCKERHUB_PASSWORD }}

      - name: SQL LINT 
        run: |
          sudo apt install npm -y
          sudo npm i -g sql-lint 
          sql-lint . trailing-whitespace || true

      - name: Build Mysql only schema to local 
        working-directory: ./mysql
        run: |
          docker build -t dongtai/dongtai-mysql-unittest:0.1.${{github.run_number}} .
          docker tag dongtai/dongtai-mysql-unittest:0.1.${{github.run_number}} dongtai/dongtai-mysql-unittest:latest

      - name: Push to DockerHub
        run: | 
          docker push dongtai/dongtai-mysql-unittest:0.1.${{github.run_number}}
          docker push dongtai/dongtai-mysql-unittest:latest
