name: Build And Push DongTai Base Image To Aliyun Repo

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    if: ${{ github.event_name == 'push' && github.repository_owner == 'HXSecurity' }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Aliyun
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_DOCKERHUB_USER }}
          password: ${{ secrets.ALIYUN_DOCKERHUB_PASSWORD }}
          
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DONGTAI_DOCKERHUB_USERNAME }}
          password: ${{ secrets.DONGTAI_DOCKERHUB_TOKEN }}
          
      - name: SQL LINT 
        run: |
          sudo apt install npm -y
          sudo npm i -g sql-lint 
          sql-lint . trailing-whitespace || true

      - name: Build and push mysql
        uses: docker/build-push-action@v3
        with:
          context: ./mysql
          push: true
          platforms: linux/amd64,linux/arm64
          tags: | 
            registry.cn-hongkong.aliyuncs.com/huoxian_pub/dongtai-mysql-unittest:1.0.${{github.run_number}}
            registry.cn-hongkong.aliyuncs.com/huoxian_pub/dongtai-mysql-unittest:latest

      - uses: actions/checkout@master
      - name: deploy to cluster
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_TEST_DATA }}
        with:
          args: |
            find .github/deploy/deploy-dongtai-mysql-test.yaml -type f -exec sed -i 's/VERSION/1.0.${{github.run_number}}/g' {} \;
            ls .github/deploy/deploy-dongtai-mysql-test.yaml | xargs -I {} kubectl apply -f {}
            kubectl rollout -n iast-test restart statefulset redis
