name: Build And Push DongTai Base Image To Aliyun Repo

on:
  push:
    branches:
      - main
      - beta
      - develop

jobs:
  build:
    if: ${{ github.event_name == 'push' && github.repository_owner == 'HXSecurity' }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Aliyun
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_DOCKERHUB_USER }}
          password: ${{ secrets.ALIYUN_DOCKERHUB_PASSWORD }}
      - name: Get the release version
        id: version
        run: echo ::set-output name=GITHUB_REF::${GITHUB_REF##*/}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DONGTAI_DOCKERHUB_USERNAME }}
          password: ${{ secrets.DONGTAI_DOCKERHUB_TOKEN }}
          
      - name: SQL LINT 
        run: |
          sudo apt install npm -y
          sudo npm i -g sql-lint 
          sql-lint . trailing-whitespace || true

      - name: Build and push mysql
        uses: docker/build-push-action@v3
        with:
          context: ./mysql
          push: true
          # platforms: linux/amd64,linux/arm64
          tags: | 
            registry.cn-hongkong.aliyuncs.com/huoxian_pub/dongtai-mysql-unittest:1.0.${{github.run_number}}-${{ steps.version.outputs.GITHUB_REF }}
            registry.cn-hongkong.aliyuncs.com/huoxian_pub/dongtai-mysql-unittest:latest
            dongtai/dongtai-mysql-unittest:1.0.${{github.run_number}}-${{ steps.version.outputs.GITHUB_REF }}
            dongtai/dongtai-mysql-unittest:latest

      - uses: actions/checkout@master
      - name: deploy to cluster
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_TEST_DATA }}
        with:
          args: |
            if [ ${{ steps.version.outputs.GITHUB_REF }} = beta ] ; then find .github/deploy/deploy-dongtai-mysql-test.yaml -type f -exec sed -i 's/iast-test/iast-beta/g' {} \; 
            kubectl rollout -n iast-${{ steps.version.outputs.GITHUB_REF }} restart statefulset redis
            elif [ ${{ steps.version.outputs.GITHUB_REF }} = develop ] ; then kubectl rollout -n iast-test restart statefulset redis
            else find .github/deploy/deploy-dongtai-mysql-test.yaml -type f -exec sed -i 's/iast-test/iast-main/g' {} \; 
            kubectl rollout -n iast-main restart statefulset redis ;fi
            find .github/deploy/deploy-dongtai-mysql-test.yaml -type f -exec sed -i 's/VERSION/1.0.${{github.run_number}}-${{ steps.version.outputs.GITHUB_REF }}/g' {} \;
            ls .github/deploy/deploy-dongtai-mysql-test.yaml | xargs -I {} kubectl apply -f {}
