name: Release DongTai IAST Base Image

on:
  push:
    branches: [ "release-*" ]

jobs:
  Release-DongTai-Infra-Service:
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 4
    steps:
      # - name: start-build
      #   uses: joelwmale/webhook-action@master
      #   with:
      #     url: ${{ secrets.WEBHOOK_URL }}
      #     body: '{"msg_type": "interactive","card": {"config": {"wide_screen_mode": true,"enable_forward": true},"elements": [{"tag": "div","text": {"content": "状态：构建开始\n项目：${{github.repository}}\n分支：${{github.ref}}\n流程：${{github.workflow}}\n构建编号：${{github.run_number}}\n触发事件：${{github.event_name}}\n提交人：${{github.actor}}\nSHA-1：${{github.sha}}\n","tag": "lark_md"}}]}}'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
    

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DONGTAI_DOCKERHUB_USERNAME }}
          password: ${{ secrets.DONGTAI_DOCKERHUB_TOKEN }}

      - name: Login to AliyunRegistry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_DOCKERHUB_USER }}
          password: ${{ secrets.ALIYUN_DOCKERHUB_PASSWORD }}

      - id: release
        run: |
          VERSION=`echo ${GITHUB_REF##*/} | awk -F'-' '{print $2}'`
          echo "::set-output name=version::$VERSION"

      - name: Setup ossutil
        uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: ${{ secrets.DONGTAI_OSS_ENDPOINT }}
          access-key-id: ${{ secrets.DONGTAI_OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.DONGTAI_OSS_ACCESS_KEY_SECRET }}
          
      - name: Push sql to OSS
        run: |
          ossutil cp -rf mysql/ --include "db.sql" --include "update-*.sql" oss://huoqi-public/iast/sql/


      - name: Build Mysql to local 
        working-directory: ./mysql
        run: |
          docker build -t dongtai/dongtai-mysql:${{ steps.release.outputs.version }} .

      - name: Tag images
        run: |
          docker tag dongtai/dongtai-mysql:${{ steps.release.outputs.version }} dongtai/dongtai-mysql:${{ steps.release.outputs.version }}
          docker tag dongtai/dongtai-mysql:${{ steps.release.outputs.version }} dongtai/dongtai-mysql:latest
          docker tag dongtai/dongtai-mysql:${{ steps.release.outputs.version }} registry.cn-beijing.aliyuncs.com/huoxian_pub/dongtai-mysql:${{ steps.release.outputs.version }}
          docker tag dongtai/dongtai-mysql:${{ steps.release.outputs.version }} registry.cn-beijing.aliyuncs.com/huoxian_pub/dongtai-mysql:latest

      - name: Build redis to local
        uses: docker/build-push-action@v2
        with:
          context: ./redis
          load: true
          tags: | 
            dongtai/dongtai-redis:${{ steps.release.outputs.version }}
            #dongtai/dongtai-redis:latest
            registry.cn-beijing.aliyuncs.com/huoxian_pub/dongtai-redis:${{ steps.release.outputs.version }}
            #registry.cn-beijing.aliyuncs.com/huoxian_pub/dongtai-redis:latest

      - name: Save image to tar file
        run: |
          docker save dongtai/dongtai-mysql:${{ steps.release.outputs.version }} | gzip > /tmp/dongtai-mysql-${{ steps.release.outputs.version }}.tar.gz
          docker save dongtai/dongtai-redis:${{ steps.release.outputs.version }} | gzip > /tmp/dongtai-redis-${{ steps.release.outputs.version }}.tar.gz

      - name: Setup Ossutil
        uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: ${{ secrets.DONGTAI_OSS_ENDPOINT }}
          access-key-id: ${{ secrets.DONGTAI_OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.DONGTAI_OSS_ACCESS_KEY_SECRET }}

      - name: Upload images to oss
        run: |
          ossutil cp -f /tmp/dongtai-mysql-${{ steps.release.outputs.version }}.tar.gz oss://huoqi-public/iast/server-package/${{ steps.release.outputs.version }}/
          ossutil cp -f /tmp/dongtai-redis-${{ steps.release.outputs.version }}.tar.gz oss://huoqi-public/iast/server-package/${{ steps.release.outputs.version }}/

      - name: Push Mysql 
        run: |
          docker images
          docker push dongtai/dongtai-mysql:${{ steps.release.outputs.version }}
          docker push registry.cn-beijing.aliyuncs.com/huoxian_pub/dongtai-mysql:${{ steps.release.outputs.version }}

      - name: Build and push Redis
        uses: docker/build-push-action@v2
        with:
          context: ./redis
          push: true
          tags: | 
            dongtai/dongtai-redis:${{ steps.release.outputs.version }}
            registry.cn-beijing.aliyuncs.com/huoxian_pub/dongtai-redis:${{ steps.release.outputs.version }}

      # - name: Build mySql to local
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./mysql
      #     load: true
      #     tags: | 
      #       dongtai/dongtai-mysql:${{ steps.release.outputs.version }}
      #       dongtai/dongtai-mysql:latest
      #       registry.cn-beijing.aliyuncs.com/huoxian_pub/dongtai-mysql:${{ steps.release.outputs.version }}
      #       registry.cn-beijing.aliyuncs.com/huoxian_pub/dongtai-mysql:latest
      
      # - name: Build redis to local
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./redis
      #     load: true
      #     tags: | 
      #       dongtai/dongtai-redis:${{ steps.release.outputs.version }}
      #       dongtai/dongtai-redis:latest
      #       registry.cn-beijing.aliyuncs.com/huoxian_pub/dongtai-redis:${{ steps.release.outputs.version }}
      #       registry.cn-beijing.aliyuncs.com/huoxian_pub/dongtai-redis:latest

      # - name: Save image to tar file
      #   run: |
      #     docker save dongtai/dongtai-mysql:${{ steps.release.outputs.version }} | gzip > /tmp/dongtai-mysql-${{ steps.release.outputs.version }}.tar.gz
      #     docker save dongtai/dongtai-redis:${{ steps.release.outputs.version }} | gzip > /tmp/dongtai-redis-${{ steps.release.outputs.version }}.tar.gz

      # - name: Setup Ossutil
      #   uses: manyuanrong/setup-ossutil@v2.0
      #   with:
      #     endpoint: ${{ secrets.DONGTAI_OSS_ENDPOINT }}
      #     access-key-id: ${{ secrets.DONGTAI_OSS_ACCESS_KEY_ID }}
      #     access-key-secret: ${{ secrets.DONGTAI_OSS_ACCESS_KEY_SECRET }}

      # - name: Upload images to oss
      #   run: |
      #     ossutil cp /tmp/dongtai-mysql-${{ steps.release.outputs.version }}.tar.gz oss://huoqi-public/iast/server-package/${{ steps.release.outputs.version }}/
      #     ossutil cp /tmp/dongtai-redis-${{ steps.release.outputs.version }}.tar.gz oss://huoqi-public/iast/server-package/${{ steps.release.outputs.version }}/


      # - name: Build and push MySql
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./mysql
      #     push: true
      #     tags: | 
      #       dongtai/dongtai-mysql:${{ steps.release.outputs.version }}
      #       dongtai/dongtai-mysql:latest
      #       registry.cn-beijing.aliyuncs.com/huoxian_pub/dongtai-mysql:${{ steps.release.outputs.version }}
      #       registry.cn-beijing.aliyuncs.com/huoxian_pub/dongtai-mysql:latest
      
      # - name: Build and push Redis
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./redis
      #     push: true
      #     tags: | 
      #       dongtai/dongtai-redis:${{ steps.release.outputs.version }}
      #       dongtai/dongtai-redis:latest
      #       registry.cn-beijing.aliyuncs.com/huoxian_pub/dongtai-redis:${{ steps.release.outputs.version }}
      #       registry.cn-beijing.aliyuncs.com/huoxian_pub/dongtai-redis:latest

      # - name: finish build
      #   uses: joelwmale/webhook-action@master
      #   with:
      #     url: ${{ secrets.WEBHOOK_URL }}
      #     body: '{"msg_type": "interactive","card": {"config": {"wide_screen_mode": true,"enable_forward": true},"elements": [{"tag": "div","text": {"content": "状态：构建完成\n项目：${{github.repository}}\n分支：${{github.ref}}\n流程：${{github.workflow}}\n构建编号：${{github.run_number}}\n触发事件：${{github.event_name}}\n提交人：${{github.actor}}\nSHA-1：${{github.sha}}\n","tag": "lark_md"}}]}}'

